version: 2

jobs:
    build:
        docker:
            - image: circleci/node:10

        working_directory: ~/rebem-helper

        steps:
            - checkout

            # - run: yarn global add bs-platform

            # Download and cache dependencies
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-
            - run: yarn install
            - save_cache:
                paths:
                    - ./node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn run clean
            - run: yarn run build
            - run: yarn test
